// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: scheduled_post.
// - Entity ID: 102019b2376dc2b721d9bb8534c2822cb3b.
// - Entity Version: 102019b2458f878772cb63866dad0847f01.
// - Task ID: 69409619feb6c5be2e057ca3.
// - Task Root ID: 694045ef165ebbbd81746188.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for ScheduledPostRetryStatus
 */
export enum ScheduledPostRetryStatus {
  Unspecified = 0,
  Pending = 1,
  Retrying = 2,
  Failed = 3,
  Success = 4,
}



/**
 * Interface for ScheduledPostModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ScheduledPostModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  post_id: string;
  publish_time: string;
  timezone: string;
  retry_count: number;
  retry_status: ScheduledPostRetryStatus;
}

/**
 * ORM class for ScheduledPost entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ScheduledPostORM {
  private static instance: ScheduledPostORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b2376dc2b721d9bb8534c2822cb3b';
    this.entityName = 'scheduled_post';
    this.entityVersion = '102019b2458f878772cb63866dad0847f01';
    this.taskId = '69409619feb6c5be2e057ca3';
    this.taskRootId = '694045ef165ebbbd81746188';
  }

  /**
   * Get singleton instance of ScheduledPostORM
   */
  public static getInstance(): ScheduledPostORM {
    if (!ScheduledPostORM.instance) {
      ScheduledPostORM.instance = new ScheduledPostORM();
    }
    
    return ScheduledPostORM.instance;
  }

  /**
   * Get all ScheduledPost records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllScheduledPost(): Promise<ScheduledPostModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new ScheduledPost record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertScheduledPost(data: ScheduledPostModel[]): Promise<ScheduledPostModel[]> {
    const structured = data.map((item) => CreateData(ScheduledPostModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all ScheduledPost records
   */
  async purgeAllScheduledPost(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List ScheduledPost records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listScheduledPost(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ScheduledPostModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get scheduled_post by Id index
   * This function gets data by index.
   */
  async getScheduledPostById(
    id: string,
  ): Promise<ScheduledPostModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) scheduled_post by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setScheduledPostById(
    id: string,
    data: ScheduledPostModel
  ): Promise<ScheduledPostModel[]> {
    const index = createIndexId(
      id
    );

    const values = ScheduledPostModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete scheduled_post by Id index
   */
  async deleteScheduledPostById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get scheduled_post by PostId index
   * This function gets data by index.
   */
  async getScheduledPostByPostId(
    post_id: string,
  ): Promise<ScheduledPostModel[]> {
    const index = createIndexPostId(
      post_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) scheduled_post by PostId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setScheduledPostByPostId(
    post_id: string,
    data: ScheduledPostModel
  ): Promise<ScheduledPostModel[]> {
    const index = createIndexPostId(
      post_id
    );

    const values = ScheduledPostModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete scheduled_post by PostId index
   */
  async deleteScheduledPostByPostId(
    post_id: string
  ): Promise<void> {
    const index = createIndexPostId(
      post_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get scheduled_post by PublishTimeRetryStatus index
   * This function gets data by index.
   */
  async getScheduledPostByPublishTimeRetryStatus(
    publish_time: string,
    retry_status: ScheduledPostRetryStatus,
  ): Promise<ScheduledPostModel[]> {
    const index = createIndexPublishTimeRetryStatus(
      publish_time,
      retry_status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) scheduled_post by PublishTimeRetryStatus index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setScheduledPostByPublishTimeRetryStatus(
    publish_time: string,
    retry_status: ScheduledPostRetryStatus,
    data: ScheduledPostModel
  ): Promise<ScheduledPostModel[]> {
    const index = createIndexPublishTimeRetryStatus(
      publish_time,
      retry_status
    );

    const values = ScheduledPostModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete scheduled_post by PublishTimeRetryStatus index
   */
  async deleteScheduledPostByPublishTimeRetryStatus(
    publish_time: string,
    retry_status: ScheduledPostRetryStatus
  ): Promise<void> {
    const index = createIndexPublishTimeRetryStatus(
      publish_time,
      retry_status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get scheduled_post by DataCreator index
   * This function gets data by index.
   */
  async getScheduledPostByDataCreator(
    data_creator: string,
  ): Promise<ScheduledPostModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) scheduled_post by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setScheduledPostByDataCreator(
    data_creator: string,
    data: ScheduledPostModel
  ): Promise<ScheduledPostModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ScheduledPostModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete scheduled_post by DataCreator index
   */
  async deleteScheduledPostByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get scheduled_post by DataUpdater index
   * This function gets data by index.
   */
  async getScheduledPostByDataUpdater(
    data_updater: string,
  ): Promise<ScheduledPostModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) scheduled_post by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setScheduledPostByDataUpdater(
    data_updater: string,
    data: ScheduledPostModel
  ): Promise<ScheduledPostModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ScheduledPostModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete scheduled_post by DataUpdater index
   */
  async deleteScheduledPostByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ScheduledPostModel data array
   */
  private resultToData(values: Data[]): ScheduledPostModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ScheduledPostModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ScheduledPostModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ScheduledPostModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ScheduledPostModel => item !== null);
  }
}

/**
 * Convert ScheduledPostModel data to Value array
 */
function ScheduledPostModelToValues(data: ScheduledPostModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'post_id', type: DataType.string, defaultValue: '' },
    { key: 'publish_time', type: DataType.string, defaultValue: '' },
    { key: 'timezone', type: DataType.string, defaultValue: '' },
    { key: 'retry_count', type: DataType.number, defaultValue: 0 },
    { key: 'retry_status', type: DataType.enumeration, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ScheduledPostModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ScheduledPostModel data
 */
function ScheduledPostModelFromValues(values: Value[]): ScheduledPostModel {
  const data: Partial<ScheduledPostModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'post_id':
        data.post_id = ParseValue(value, DataType.string) as string;
        break;
      case 'publish_time':
        data.publish_time = ParseValue(value, DataType.string) as string;
        break;
      case 'timezone':
        data.timezone = ParseValue(value, DataType.string) as string;
        break;
      case 'retry_count':
        data.retry_count = ParseValue(value, DataType.number) as number;
        break;
      case 'retry_status':
        data.retry_status = ParseValue(value, DataType.enumeration) as ScheduledPostRetryStatus;
        break;
    }
  }
  
  return data as ScheduledPostModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for PostId fields
 */
function createIndexPostId(
  post_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, post_id, 'post_id'),
  ];

  return {
    fields: ['post_id'],
    values
  };
}
/**
 * Create index for PublishTimeRetryStatus fields
 */
function createIndexPublishTimeRetryStatus(
  publish_time: string,
  retry_status: ScheduledPostRetryStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, publish_time, 'publish_time'),
    CreateValue(DataType.enumeration, retry_status, 'retry_status'),
  ];

  return {
    fields: ['publish_time', 'retry_status'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default ScheduledPostORM;