// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: asset_library.
// - Entity ID: 102019b2376dc2b7956bd5047b99bbccd54.
// - Entity Version: 102019b2458f878772cb63866dad0847f01.
// - Task ID: 69409619feb6c5be2e057ca3.
// - Task Root ID: 694045ef165ebbbd81746188.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for AssetLibraryType
 */
export enum AssetLibraryType {
  Unspecified = 0,
  Image = 1,
  Video = 2,
  Template = 3,
  Hashtags = 4,
}



/**
 * Interface for AssetLibraryModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface AssetLibraryModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  type: AssetLibraryType;
  url?: string | null;
  metadata_json?: string | null;
  version: string;
  tags?: string[] | null;
  org_id: string;
}

/**
 * ORM class for AssetLibrary entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class AssetLibraryORM {
  private static instance: AssetLibraryORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b2376dc2b7956bd5047b99bbccd54';
    this.entityName = 'asset_library';
    this.entityVersion = '102019b2458f878772cb63866dad0847f01';
    this.taskId = '69409619feb6c5be2e057ca3';
    this.taskRootId = '694045ef165ebbbd81746188';
  }

  /**
   * Get singleton instance of AssetLibraryORM
   */
  public static getInstance(): AssetLibraryORM {
    if (!AssetLibraryORM.instance) {
      AssetLibraryORM.instance = new AssetLibraryORM();
    }
    
    return AssetLibraryORM.instance;
  }

  /**
   * Get all AssetLibrary records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllAssetLibrary(): Promise<AssetLibraryModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new AssetLibrary record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertAssetLibrary(data: AssetLibraryModel[]): Promise<AssetLibraryModel[]> {
    const structured = data.map((item) => CreateData(AssetLibraryModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all AssetLibrary records
   */
  async purgeAllAssetLibrary(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List AssetLibrary records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listAssetLibrary(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[AssetLibraryModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get asset_library by Id index
   * This function gets data by index.
   */
  async getAssetLibraryById(
    id: string,
  ): Promise<AssetLibraryModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) asset_library by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAssetLibraryById(
    id: string,
    data: AssetLibraryModel
  ): Promise<AssetLibraryModel[]> {
    const index = createIndexId(
      id
    );

    const values = AssetLibraryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete asset_library by Id index
   */
  async deleteAssetLibraryById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get asset_library by OrgIdType index
   * This function gets data by index.
   */
  async getAssetLibraryByOrgIdType(
    org_id: string,
    type: AssetLibraryType,
  ): Promise<AssetLibraryModel[]> {
    const index = createIndexOrgIdType(
      org_id,
      type
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) asset_library by OrgIdType index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAssetLibraryByOrgIdType(
    org_id: string,
    type: AssetLibraryType,
    data: AssetLibraryModel
  ): Promise<AssetLibraryModel[]> {
    const index = createIndexOrgIdType(
      org_id,
      type
    );

    const values = AssetLibraryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete asset_library by OrgIdType index
   */
  async deleteAssetLibraryByOrgIdType(
    org_id: string,
    type: AssetLibraryType
  ): Promise<void> {
    const index = createIndexOrgIdType(
      org_id,
      type
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get asset_library by DataCreator index
   * This function gets data by index.
   */
  async getAssetLibraryByDataCreator(
    data_creator: string,
  ): Promise<AssetLibraryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) asset_library by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAssetLibraryByDataCreator(
    data_creator: string,
    data: AssetLibraryModel
  ): Promise<AssetLibraryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = AssetLibraryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete asset_library by DataCreator index
   */
  async deleteAssetLibraryByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get asset_library by DataUpdater index
   * This function gets data by index.
   */
  async getAssetLibraryByDataUpdater(
    data_updater: string,
  ): Promise<AssetLibraryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) asset_library by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAssetLibraryByDataUpdater(
    data_updater: string,
    data: AssetLibraryModel
  ): Promise<AssetLibraryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = AssetLibraryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete asset_library by DataUpdater index
   */
  async deleteAssetLibraryByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to AssetLibraryModel data array
   */
  private resultToData(values: Data[]): AssetLibraryModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return AssetLibraryModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as AssetLibraryModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized AssetLibraryModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is AssetLibraryModel => item !== null);
  }
}

/**
 * Convert AssetLibraryModel data to Value array
 */
function AssetLibraryModelToValues(data: AssetLibraryModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'url', type: DataType.string, defaultValue: null },
    { key: 'metadata_json', type: DataType.string, defaultValue: null },
    { key: 'version', type: DataType.string, defaultValue: '' },
    { key: 'tags', type: DataType.array, defaultValue: null },
    { key: 'org_id', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof AssetLibraryModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to AssetLibraryModel data
 */
function AssetLibraryModelFromValues(values: Value[]): AssetLibraryModel {
  const data: Partial<AssetLibraryModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'type':
        data.type = ParseValue(value, DataType.enumeration) as AssetLibraryType;
        break;
      case 'url':
        data.url = ParseValue(value, DataType.string) as string | null;
        break;
      case 'metadata_json':
        data.metadata_json = ParseValue(value, DataType.string) as string | null;
        break;
      case 'version':
        data.version = ParseValue(value, DataType.string) as string;
        break;
      case 'tags':
        data.tags = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'org_id':
        data.org_id = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as AssetLibraryModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for OrgIdType fields
 */
function createIndexOrgIdType(
  org_id: string,
  type: AssetLibraryType
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, org_id, 'org_id'),
    CreateValue(DataType.enumeration, type, 'type'),
  ];

  return {
    fields: ['org_id', 'type'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default AssetLibraryORM;