// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: conversation.
// - Entity ID: 102019b2376dc2b75708f2367f811b90b1d.
// - Entity Version: 102019b2458f878772cb63866dad0847f01.
// - Task ID: 69409619feb6c5be2e057ca3.
// - Task Root ID: 694045ef165ebbbd81746188.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for ConversationMessageType
 */
export enum ConversationMessageType {
  Unspecified = 0,
  Comment = 1,
  Mention = 2,
  DM = 3,
}
/**
 * Enumeration for ConversationStatus
 */
export enum ConversationStatus {
  Unspecified = 0,
  Unread = 1,
  Read = 2,
  Replied = 3,
  Archived = 4,
}



/**
 * Interface for ConversationModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ConversationModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  platform: string;
  message_type: ConversationMessageType;
  content?: string | null;
  thread_id?: string | null;
  assigned_user_id?: string | null;
  status: ConversationStatus;
  org_id: string;
}

/**
 * ORM class for Conversation entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ConversationORM {
  private static instance: ConversationORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b2376dc2b75708f2367f811b90b1d';
    this.entityName = 'conversation';
    this.entityVersion = '102019b2458f878772cb63866dad0847f01';
    this.taskId = '69409619feb6c5be2e057ca3';
    this.taskRootId = '694045ef165ebbbd81746188';
  }

  /**
   * Get singleton instance of ConversationORM
   */
  public static getInstance(): ConversationORM {
    if (!ConversationORM.instance) {
      ConversationORM.instance = new ConversationORM();
    }
    
    return ConversationORM.instance;
  }

  /**
   * Get all Conversation records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllConversation(): Promise<ConversationModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Conversation record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertConversation(data: ConversationModel[]): Promise<ConversationModel[]> {
    const structured = data.map((item) => CreateData(ConversationModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Conversation records
   */
  async purgeAllConversation(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Conversation records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listConversation(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ConversationModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get conversation by Id index
   * This function gets data by index.
   */
  async getConversationById(
    id: string,
  ): Promise<ConversationModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) conversation by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConversationById(
    id: string,
    data: ConversationModel
  ): Promise<ConversationModel[]> {
    const index = createIndexId(
      id
    );

    const values = ConversationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete conversation by Id index
   */
  async deleteConversationById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get conversation by OrgIdStatus index
   * This function gets data by index.
   */
  async getConversationByOrgIdStatus(
    org_id: string,
    status: ConversationStatus,
  ): Promise<ConversationModel[]> {
    const index = createIndexOrgIdStatus(
      org_id,
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) conversation by OrgIdStatus index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConversationByOrgIdStatus(
    org_id: string,
    status: ConversationStatus,
    data: ConversationModel
  ): Promise<ConversationModel[]> {
    const index = createIndexOrgIdStatus(
      org_id,
      status
    );

    const values = ConversationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete conversation by OrgIdStatus index
   */
  async deleteConversationByOrgIdStatus(
    org_id: string,
    status: ConversationStatus
  ): Promise<void> {
    const index = createIndexOrgIdStatus(
      org_id,
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get conversation by AssignedUserId index
   * This function gets data by index.
   */
  async getConversationByAssignedUserId(
    assigned_user_id: string,
  ): Promise<ConversationModel[]> {
    const index = createIndexAssignedUserId(
      assigned_user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) conversation by AssignedUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConversationByAssignedUserId(
    assigned_user_id: string,
    data: ConversationModel
  ): Promise<ConversationModel[]> {
    const index = createIndexAssignedUserId(
      assigned_user_id
    );

    const values = ConversationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete conversation by AssignedUserId index
   */
  async deleteConversationByAssignedUserId(
    assigned_user_id: string
  ): Promise<void> {
    const index = createIndexAssignedUserId(
      assigned_user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get conversation by ThreadId index
   * This function gets data by index.
   */
  async getConversationByThreadId(
    thread_id: string,
  ): Promise<ConversationModel[]> {
    const index = createIndexThreadId(
      thread_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) conversation by ThreadId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConversationByThreadId(
    thread_id: string,
    data: ConversationModel
  ): Promise<ConversationModel[]> {
    const index = createIndexThreadId(
      thread_id
    );

    const values = ConversationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete conversation by ThreadId index
   */
  async deleteConversationByThreadId(
    thread_id: string
  ): Promise<void> {
    const index = createIndexThreadId(
      thread_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get conversation by DataCreator index
   * This function gets data by index.
   */
  async getConversationByDataCreator(
    data_creator: string,
  ): Promise<ConversationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) conversation by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConversationByDataCreator(
    data_creator: string,
    data: ConversationModel
  ): Promise<ConversationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ConversationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete conversation by DataCreator index
   */
  async deleteConversationByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get conversation by DataUpdater index
   * This function gets data by index.
   */
  async getConversationByDataUpdater(
    data_updater: string,
  ): Promise<ConversationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) conversation by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConversationByDataUpdater(
    data_updater: string,
    data: ConversationModel
  ): Promise<ConversationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ConversationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete conversation by DataUpdater index
   */
  async deleteConversationByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ConversationModel data array
   */
  private resultToData(values: Data[]): ConversationModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ConversationModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ConversationModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ConversationModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ConversationModel => item !== null);
  }
}

/**
 * Convert ConversationModel data to Value array
 */
function ConversationModelToValues(data: ConversationModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'platform', type: DataType.string, defaultValue: '' },
    { key: 'message_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'content', type: DataType.string, defaultValue: null },
    { key: 'thread_id', type: DataType.string, defaultValue: null },
    { key: 'assigned_user_id', type: DataType.string, defaultValue: null },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'org_id', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ConversationModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ConversationModel data
 */
function ConversationModelFromValues(values: Value[]): ConversationModel {
  const data: Partial<ConversationModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'platform':
        data.platform = ParseValue(value, DataType.string) as string;
        break;
      case 'message_type':
        data.message_type = ParseValue(value, DataType.enumeration) as ConversationMessageType;
        break;
      case 'content':
        data.content = ParseValue(value, DataType.string) as string | null;
        break;
      case 'thread_id':
        data.thread_id = ParseValue(value, DataType.string) as string | null;
        break;
      case 'assigned_user_id':
        data.assigned_user_id = ParseValue(value, DataType.string) as string | null;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as ConversationStatus;
        break;
      case 'org_id':
        data.org_id = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as ConversationModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for OrgIdStatus fields
 */
function createIndexOrgIdStatus(
  org_id: string,
  status: ConversationStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, org_id, 'org_id'),
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['org_id', 'status'],
    values
  };
}
/**
 * Create index for AssignedUserId fields
 */
function createIndexAssignedUserId(
  assigned_user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, assigned_user_id, 'assigned_user_id'),
  ];

  return {
    fields: ['assigned_user_id'],
    values
  };
}
/**
 * Create index for ThreadId fields
 */
function createIndexThreadId(
  thread_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, thread_id, 'thread_id'),
  ];

  return {
    fields: ['thread_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default ConversationORM;