// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: approval_workflow.
// - Entity ID: 102019b2376dc2c733998976f255dc64597.
// - Entity Version: 102019b2458f878772cb63866dad0847f01.
// - Task ID: 69409619feb6c5be2e057ca3.
// - Task Root ID: 694045ef165ebbbd81746188.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for ApprovalWorkflowStatus
 */
export enum ApprovalWorkflowStatus {
  Unspecified = 0,
  Pending = 1,
  Approved = 2,
  Rejected = 3,
}



/**
 * Interface for ApprovalWorkflowModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ApprovalWorkflowModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  post_id: string;
  approver_user_id: string;
  status: ApprovalWorkflowStatus;
  approved_at?: string | null;
  rejection_reason?: string | null;
}

/**
 * ORM class for ApprovalWorkflow entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ApprovalWorkflowORM {
  private static instance: ApprovalWorkflowORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b2376dc2c733998976f255dc64597';
    this.entityName = 'approval_workflow';
    this.entityVersion = '102019b2458f878772cb63866dad0847f01';
    this.taskId = '69409619feb6c5be2e057ca3';
    this.taskRootId = '694045ef165ebbbd81746188';
  }

  /**
   * Get singleton instance of ApprovalWorkflowORM
   */
  public static getInstance(): ApprovalWorkflowORM {
    if (!ApprovalWorkflowORM.instance) {
      ApprovalWorkflowORM.instance = new ApprovalWorkflowORM();
    }
    
    return ApprovalWorkflowORM.instance;
  }

  /**
   * Get all ApprovalWorkflow records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllApprovalWorkflow(): Promise<ApprovalWorkflowModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new ApprovalWorkflow record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertApprovalWorkflow(data: ApprovalWorkflowModel[]): Promise<ApprovalWorkflowModel[]> {
    const structured = data.map((item) => CreateData(ApprovalWorkflowModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all ApprovalWorkflow records
   */
  async purgeAllApprovalWorkflow(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List ApprovalWorkflow records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listApprovalWorkflow(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ApprovalWorkflowModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get approval_workflow by Id index
   * This function gets data by index.
   */
  async getApprovalWorkflowById(
    id: string,
  ): Promise<ApprovalWorkflowModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) approval_workflow by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setApprovalWorkflowById(
    id: string,
    data: ApprovalWorkflowModel
  ): Promise<ApprovalWorkflowModel[]> {
    const index = createIndexId(
      id
    );

    const values = ApprovalWorkflowModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete approval_workflow by Id index
   */
  async deleteApprovalWorkflowById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get approval_workflow by PostId index
   * This function gets data by index.
   */
  async getApprovalWorkflowByPostId(
    post_id: string,
  ): Promise<ApprovalWorkflowModel[]> {
    const index = createIndexPostId(
      post_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) approval_workflow by PostId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setApprovalWorkflowByPostId(
    post_id: string,
    data: ApprovalWorkflowModel
  ): Promise<ApprovalWorkflowModel[]> {
    const index = createIndexPostId(
      post_id
    );

    const values = ApprovalWorkflowModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete approval_workflow by PostId index
   */
  async deleteApprovalWorkflowByPostId(
    post_id: string
  ): Promise<void> {
    const index = createIndexPostId(
      post_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get approval_workflow by ApproverUserIdStatus index
   * This function gets data by index.
   */
  async getApprovalWorkflowByApproverUserIdStatus(
    approver_user_id: string,
    status: ApprovalWorkflowStatus,
  ): Promise<ApprovalWorkflowModel[]> {
    const index = createIndexApproverUserIdStatus(
      approver_user_id,
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) approval_workflow by ApproverUserIdStatus index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setApprovalWorkflowByApproverUserIdStatus(
    approver_user_id: string,
    status: ApprovalWorkflowStatus,
    data: ApprovalWorkflowModel
  ): Promise<ApprovalWorkflowModel[]> {
    const index = createIndexApproverUserIdStatus(
      approver_user_id,
      status
    );

    const values = ApprovalWorkflowModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete approval_workflow by ApproverUserIdStatus index
   */
  async deleteApprovalWorkflowByApproverUserIdStatus(
    approver_user_id: string,
    status: ApprovalWorkflowStatus
  ): Promise<void> {
    const index = createIndexApproverUserIdStatus(
      approver_user_id,
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get approval_workflow by DataCreator index
   * This function gets data by index.
   */
  async getApprovalWorkflowByDataCreator(
    data_creator: string,
  ): Promise<ApprovalWorkflowModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) approval_workflow by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setApprovalWorkflowByDataCreator(
    data_creator: string,
    data: ApprovalWorkflowModel
  ): Promise<ApprovalWorkflowModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ApprovalWorkflowModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete approval_workflow by DataCreator index
   */
  async deleteApprovalWorkflowByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get approval_workflow by DataUpdater index
   * This function gets data by index.
   */
  async getApprovalWorkflowByDataUpdater(
    data_updater: string,
  ): Promise<ApprovalWorkflowModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) approval_workflow by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setApprovalWorkflowByDataUpdater(
    data_updater: string,
    data: ApprovalWorkflowModel
  ): Promise<ApprovalWorkflowModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ApprovalWorkflowModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete approval_workflow by DataUpdater index
   */
  async deleteApprovalWorkflowByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ApprovalWorkflowModel data array
   */
  private resultToData(values: Data[]): ApprovalWorkflowModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ApprovalWorkflowModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ApprovalWorkflowModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ApprovalWorkflowModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ApprovalWorkflowModel => item !== null);
  }
}

/**
 * Convert ApprovalWorkflowModel data to Value array
 */
function ApprovalWorkflowModelToValues(data: ApprovalWorkflowModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'post_id', type: DataType.string, defaultValue: '' },
    { key: 'approver_user_id', type: DataType.string, defaultValue: '' },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'approved_at', type: DataType.string, defaultValue: null },
    { key: 'rejection_reason', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ApprovalWorkflowModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ApprovalWorkflowModel data
 */
function ApprovalWorkflowModelFromValues(values: Value[]): ApprovalWorkflowModel {
  const data: Partial<ApprovalWorkflowModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'post_id':
        data.post_id = ParseValue(value, DataType.string) as string;
        break;
      case 'approver_user_id':
        data.approver_user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as ApprovalWorkflowStatus;
        break;
      case 'approved_at':
        data.approved_at = ParseValue(value, DataType.string) as string | null;
        break;
      case 'rejection_reason':
        data.rejection_reason = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as ApprovalWorkflowModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for PostId fields
 */
function createIndexPostId(
  post_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, post_id, 'post_id'),
  ];

  return {
    fields: ['post_id'],
    values
  };
}
/**
 * Create index for ApproverUserIdStatus fields
 */
function createIndexApproverUserIdStatus(
  approver_user_id: string,
  status: ApprovalWorkflowStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, approver_user_id, 'approver_user_id'),
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['approver_user_id', 'status'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default ApprovalWorkflowORM;