// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: alert.
// - Entity ID: 102019b2376dc2a7d94b5df9158ab2e018b.
// - Entity Version: 102019b2458f878772cb63866dad0847f01.
// - Task ID: 69409619feb6c5be2e057ca3.
// - Task Root ID: 694045ef165ebbbd81746188.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for AlertModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface AlertModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  keyword: string;
  platform: string;
  notification_config_json: string;
  trigger_count: number;
  org_id: string;
}

/**
 * ORM class for Alert entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class AlertORM {
  private static instance: AlertORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b2376dc2a7d94b5df9158ab2e018b';
    this.entityName = 'alert';
    this.entityVersion = '102019b2458f878772cb63866dad0847f01';
    this.taskId = '69409619feb6c5be2e057ca3';
    this.taskRootId = '694045ef165ebbbd81746188';
  }

  /**
   * Get singleton instance of AlertORM
   */
  public static getInstance(): AlertORM {
    if (!AlertORM.instance) {
      AlertORM.instance = new AlertORM();
    }
    
    return AlertORM.instance;
  }

  /**
   * Get all Alert records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllAlert(): Promise<AlertModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Alert record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertAlert(data: AlertModel[]): Promise<AlertModel[]> {
    const structured = data.map((item) => CreateData(AlertModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Alert records
   */
  async purgeAllAlert(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Alert records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listAlert(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[AlertModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get alert by Id index
   * This function gets data by index.
   */
  async getAlertById(
    id: string,
  ): Promise<AlertModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) alert by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAlertById(
    id: string,
    data: AlertModel
  ): Promise<AlertModel[]> {
    const index = createIndexId(
      id
    );

    const values = AlertModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete alert by Id index
   */
  async deleteAlertById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get alert by KeywordOrgId index
   * This function gets data by index.
   */
  async getAlertByKeywordOrgId(
    keyword: string,
    org_id: string,
  ): Promise<AlertModel[]> {
    const index = createIndexKeywordOrgId(
      keyword,
      org_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) alert by KeywordOrgId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAlertByKeywordOrgId(
    keyword: string,
    org_id: string,
    data: AlertModel
  ): Promise<AlertModel[]> {
    const index = createIndexKeywordOrgId(
      keyword,
      org_id
    );

    const values = AlertModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete alert by KeywordOrgId index
   */
  async deleteAlertByKeywordOrgId(
    keyword: string,
    org_id: string
  ): Promise<void> {
    const index = createIndexKeywordOrgId(
      keyword,
      org_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get alert by DataCreator index
   * This function gets data by index.
   */
  async getAlertByDataCreator(
    data_creator: string,
  ): Promise<AlertModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) alert by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAlertByDataCreator(
    data_creator: string,
    data: AlertModel
  ): Promise<AlertModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = AlertModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete alert by DataCreator index
   */
  async deleteAlertByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get alert by DataUpdater index
   * This function gets data by index.
   */
  async getAlertByDataUpdater(
    data_updater: string,
  ): Promise<AlertModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) alert by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAlertByDataUpdater(
    data_updater: string,
    data: AlertModel
  ): Promise<AlertModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = AlertModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete alert by DataUpdater index
   */
  async deleteAlertByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to AlertModel data array
   */
  private resultToData(values: Data[]): AlertModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return AlertModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as AlertModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized AlertModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is AlertModel => item !== null);
  }
}

/**
 * Convert AlertModel data to Value array
 */
function AlertModelToValues(data: AlertModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'keyword', type: DataType.string, defaultValue: '' },
    { key: 'platform', type: DataType.string, defaultValue: '' },
    { key: 'notification_config_json', type: DataType.string, defaultValue: '' },
    { key: 'trigger_count', type: DataType.number, defaultValue: 0 },
    { key: 'org_id', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof AlertModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to AlertModel data
 */
function AlertModelFromValues(values: Value[]): AlertModel {
  const data: Partial<AlertModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'keyword':
        data.keyword = ParseValue(value, DataType.string) as string;
        break;
      case 'platform':
        data.platform = ParseValue(value, DataType.string) as string;
        break;
      case 'notification_config_json':
        data.notification_config_json = ParseValue(value, DataType.string) as string;
        break;
      case 'trigger_count':
        data.trigger_count = ParseValue(value, DataType.number) as number;
        break;
      case 'org_id':
        data.org_id = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as AlertModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for KeywordOrgId fields
 */
function createIndexKeywordOrgId(
  keyword: string,
  org_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, keyword, 'keyword'),
    CreateValue(DataType.string, org_id, 'org_id'),
  ];

  return {
    fields: ['keyword', 'org_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default AlertORM;