// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: team_note.
// - Entity ID: 102019b2376dc2c755a8a50685a4c6e7f8a.
// - Entity Version: 102019b2458f878772cb63866dad0847f01.
// - Task ID: 69409619feb6c5be2e057ca3.
// - Task Root ID: 694045ef165ebbbd81746188.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for TeamNoteModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface TeamNoteModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  resource_type: string;
  resource_id: string;
  content: string;
  author_user_id: string;
  org_id: string;
}

/**
 * ORM class for TeamNote entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class TeamNoteORM {
  private static instance: TeamNoteORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b2376dc2c755a8a50685a4c6e7f8a';
    this.entityName = 'team_note';
    this.entityVersion = '102019b2458f878772cb63866dad0847f01';
    this.taskId = '69409619feb6c5be2e057ca3';
    this.taskRootId = '694045ef165ebbbd81746188';
  }

  /**
   * Get singleton instance of TeamNoteORM
   */
  public static getInstance(): TeamNoteORM {
    if (!TeamNoteORM.instance) {
      TeamNoteORM.instance = new TeamNoteORM();
    }
    
    return TeamNoteORM.instance;
  }

  /**
   * Get all TeamNote records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllTeamNote(): Promise<TeamNoteModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new TeamNote record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertTeamNote(data: TeamNoteModel[]): Promise<TeamNoteModel[]> {
    const structured = data.map((item) => CreateData(TeamNoteModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all TeamNote records
   */
  async purgeAllTeamNote(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List TeamNote records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listTeamNote(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[TeamNoteModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get team_note by Id index
   * This function gets data by index.
   */
  async getTeamNoteById(
    id: string,
  ): Promise<TeamNoteModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) team_note by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTeamNoteById(
    id: string,
    data: TeamNoteModel
  ): Promise<TeamNoteModel[]> {
    const index = createIndexId(
      id
    );

    const values = TeamNoteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete team_note by Id index
   */
  async deleteTeamNoteById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get team_note by ResourceIdResourceType index
   * This function gets data by index.
   */
  async getTeamNoteByResourceIdResourceType(
    resource_id: string,
    resource_type: string,
  ): Promise<TeamNoteModel[]> {
    const index = createIndexResourceIdResourceType(
      resource_id,
      resource_type
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) team_note by ResourceIdResourceType index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTeamNoteByResourceIdResourceType(
    resource_id: string,
    resource_type: string,
    data: TeamNoteModel
  ): Promise<TeamNoteModel[]> {
    const index = createIndexResourceIdResourceType(
      resource_id,
      resource_type
    );

    const values = TeamNoteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete team_note by ResourceIdResourceType index
   */
  async deleteTeamNoteByResourceIdResourceType(
    resource_id: string,
    resource_type: string
  ): Promise<void> {
    const index = createIndexResourceIdResourceType(
      resource_id,
      resource_type
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get team_note by OrgId index
   * This function gets data by index.
   */
  async getTeamNoteByOrgId(
    org_id: string,
  ): Promise<TeamNoteModel[]> {
    const index = createIndexOrgId(
      org_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) team_note by OrgId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTeamNoteByOrgId(
    org_id: string,
    data: TeamNoteModel
  ): Promise<TeamNoteModel[]> {
    const index = createIndexOrgId(
      org_id
    );

    const values = TeamNoteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete team_note by OrgId index
   */
  async deleteTeamNoteByOrgId(
    org_id: string
  ): Promise<void> {
    const index = createIndexOrgId(
      org_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get team_note by DataCreator index
   * This function gets data by index.
   */
  async getTeamNoteByDataCreator(
    data_creator: string,
  ): Promise<TeamNoteModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) team_note by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTeamNoteByDataCreator(
    data_creator: string,
    data: TeamNoteModel
  ): Promise<TeamNoteModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = TeamNoteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete team_note by DataCreator index
   */
  async deleteTeamNoteByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get team_note by DataUpdater index
   * This function gets data by index.
   */
  async getTeamNoteByDataUpdater(
    data_updater: string,
  ): Promise<TeamNoteModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) team_note by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTeamNoteByDataUpdater(
    data_updater: string,
    data: TeamNoteModel
  ): Promise<TeamNoteModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = TeamNoteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete team_note by DataUpdater index
   */
  async deleteTeamNoteByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to TeamNoteModel data array
   */
  private resultToData(values: Data[]): TeamNoteModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return TeamNoteModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as TeamNoteModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized TeamNoteModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is TeamNoteModel => item !== null);
  }
}

/**
 * Convert TeamNoteModel data to Value array
 */
function TeamNoteModelToValues(data: TeamNoteModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'resource_type', type: DataType.string, defaultValue: '' },
    { key: 'resource_id', type: DataType.string, defaultValue: '' },
    { key: 'content', type: DataType.string, defaultValue: '' },
    { key: 'author_user_id', type: DataType.string, defaultValue: '' },
    { key: 'org_id', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof TeamNoteModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to TeamNoteModel data
 */
function TeamNoteModelFromValues(values: Value[]): TeamNoteModel {
  const data: Partial<TeamNoteModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'resource_type':
        data.resource_type = ParseValue(value, DataType.string) as string;
        break;
      case 'resource_id':
        data.resource_id = ParseValue(value, DataType.string) as string;
        break;
      case 'content':
        data.content = ParseValue(value, DataType.string) as string;
        break;
      case 'author_user_id':
        data.author_user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'org_id':
        data.org_id = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as TeamNoteModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for ResourceIdResourceType fields
 */
function createIndexResourceIdResourceType(
  resource_id: string,
  resource_type: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, resource_id, 'resource_id'),
    CreateValue(DataType.string, resource_type, 'resource_type'),
  ];

  return {
    fields: ['resource_id', 'resource_type'],
    values
  };
}
/**
 * Create index for OrgId fields
 */
function createIndexOrgId(
  org_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, org_id, 'org_id'),
  ];

  return {
    fields: ['org_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default TeamNoteORM;