// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: analytic_data.
// - Entity ID: 102019b2376dc2b7d1e817fb17b1ef49351.
// - Entity Version: 102019b2458f878772cb63866dad0847f01.
// - Task ID: 69409619feb6c5be2e057ca3.
// - Task Root ID: 694045ef165ebbbd81746188.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for AnalyticDataModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface AnalyticDataModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  post_id: string;
  impressions: number;
  reach: number;
  engagement_rate: number;
  clicks: number;
  views: number;
  shares: number;
  comments_count: number;
  recorded_at: string;
}

/**
 * ORM class for AnalyticData entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class AnalyticDataORM {
  private static instance: AnalyticDataORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b2376dc2b7d1e817fb17b1ef49351';
    this.entityName = 'analytic_data';
    this.entityVersion = '102019b2458f878772cb63866dad0847f01';
    this.taskId = '69409619feb6c5be2e057ca3';
    this.taskRootId = '694045ef165ebbbd81746188';
  }

  /**
   * Get singleton instance of AnalyticDataORM
   */
  public static getInstance(): AnalyticDataORM {
    if (!AnalyticDataORM.instance) {
      AnalyticDataORM.instance = new AnalyticDataORM();
    }
    
    return AnalyticDataORM.instance;
  }

  /**
   * Get all AnalyticData records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllAnalyticData(): Promise<AnalyticDataModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new AnalyticData record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertAnalyticData(data: AnalyticDataModel[]): Promise<AnalyticDataModel[]> {
    const structured = data.map((item) => CreateData(AnalyticDataModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all AnalyticData records
   */
  async purgeAllAnalyticData(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List AnalyticData records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listAnalyticData(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[AnalyticDataModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get analytic_data by Id index
   * This function gets data by index.
   */
  async getAnalyticDataById(
    id: string,
  ): Promise<AnalyticDataModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) analytic_data by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAnalyticDataById(
    id: string,
    data: AnalyticDataModel
  ): Promise<AnalyticDataModel[]> {
    const index = createIndexId(
      id
    );

    const values = AnalyticDataModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete analytic_data by Id index
   */
  async deleteAnalyticDataById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get analytic_data by PostIdRecordedAt index
   * This function gets data by index.
   */
  async getAnalyticDataByPostIdRecordedAt(
    post_id: string,
    recorded_at: string,
  ): Promise<AnalyticDataModel[]> {
    const index = createIndexPostIdRecordedAt(
      post_id,
      recorded_at
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) analytic_data by PostIdRecordedAt index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAnalyticDataByPostIdRecordedAt(
    post_id: string,
    recorded_at: string,
    data: AnalyticDataModel
  ): Promise<AnalyticDataModel[]> {
    const index = createIndexPostIdRecordedAt(
      post_id,
      recorded_at
    );

    const values = AnalyticDataModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete analytic_data by PostIdRecordedAt index
   */
  async deleteAnalyticDataByPostIdRecordedAt(
    post_id: string,
    recorded_at: string
  ): Promise<void> {
    const index = createIndexPostIdRecordedAt(
      post_id,
      recorded_at
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get analytic_data by DataCreator index
   * This function gets data by index.
   */
  async getAnalyticDataByDataCreator(
    data_creator: string,
  ): Promise<AnalyticDataModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) analytic_data by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAnalyticDataByDataCreator(
    data_creator: string,
    data: AnalyticDataModel
  ): Promise<AnalyticDataModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = AnalyticDataModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete analytic_data by DataCreator index
   */
  async deleteAnalyticDataByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get analytic_data by DataUpdater index
   * This function gets data by index.
   */
  async getAnalyticDataByDataUpdater(
    data_updater: string,
  ): Promise<AnalyticDataModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) analytic_data by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAnalyticDataByDataUpdater(
    data_updater: string,
    data: AnalyticDataModel
  ): Promise<AnalyticDataModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = AnalyticDataModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete analytic_data by DataUpdater index
   */
  async deleteAnalyticDataByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to AnalyticDataModel data array
   */
  private resultToData(values: Data[]): AnalyticDataModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return AnalyticDataModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as AnalyticDataModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized AnalyticDataModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is AnalyticDataModel => item !== null);
  }
}

/**
 * Convert AnalyticDataModel data to Value array
 */
function AnalyticDataModelToValues(data: AnalyticDataModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'post_id', type: DataType.string, defaultValue: '' },
    { key: 'impressions', type: DataType.number, defaultValue: 0 },
    { key: 'reach', type: DataType.number, defaultValue: 0 },
    { key: 'engagement_rate', type: DataType.number, defaultValue: 0 },
    { key: 'clicks', type: DataType.number, defaultValue: 0 },
    { key: 'views', type: DataType.number, defaultValue: 0 },
    { key: 'shares', type: DataType.number, defaultValue: 0 },
    { key: 'comments_count', type: DataType.number, defaultValue: 0 },
    { key: 'recorded_at', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof AnalyticDataModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to AnalyticDataModel data
 */
function AnalyticDataModelFromValues(values: Value[]): AnalyticDataModel {
  const data: Partial<AnalyticDataModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'post_id':
        data.post_id = ParseValue(value, DataType.string) as string;
        break;
      case 'impressions':
        data.impressions = ParseValue(value, DataType.number) as number;
        break;
      case 'reach':
        data.reach = ParseValue(value, DataType.number) as number;
        break;
      case 'engagement_rate':
        data.engagement_rate = ParseValue(value, DataType.number) as number;
        break;
      case 'clicks':
        data.clicks = ParseValue(value, DataType.number) as number;
        break;
      case 'views':
        data.views = ParseValue(value, DataType.number) as number;
        break;
      case 'shares':
        data.shares = ParseValue(value, DataType.number) as number;
        break;
      case 'comments_count':
        data.comments_count = ParseValue(value, DataType.number) as number;
        break;
      case 'recorded_at':
        data.recorded_at = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as AnalyticDataModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for PostIdRecordedAt fields
 */
function createIndexPostIdRecordedAt(
  post_id: string,
  recorded_at: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, post_id, 'post_id'),
    CreateValue(DataType.string, recorded_at, 'recorded_at'),
  ];

  return {
    fields: ['post_id', 'recorded_at'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default AnalyticDataORM;