// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: audit_log.
// - Entity ID: 102019b2376dc2c71218af046d00e0dafc9.
// - Entity Version: 102019b2458f878772cb63866dad0847f01.
// - Task ID: 69409619feb6c5be2e057ca3.
// - Task Root ID: 694045ef165ebbbd81746188.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for AuditLogModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface AuditLogModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  action_type: string;
  resource_type: string;
  resource_id: string;
  details_json?: string | null;
  org_id: string;
}

/**
 * ORM class for AuditLog entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class AuditLogORM {
  private static instance: AuditLogORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b2376dc2c71218af046d00e0dafc9';
    this.entityName = 'audit_log';
    this.entityVersion = '102019b2458f878772cb63866dad0847f01';
    this.taskId = '69409619feb6c5be2e057ca3';
    this.taskRootId = '694045ef165ebbbd81746188';
  }

  /**
   * Get singleton instance of AuditLogORM
   */
  public static getInstance(): AuditLogORM {
    if (!AuditLogORM.instance) {
      AuditLogORM.instance = new AuditLogORM();
    }
    
    return AuditLogORM.instance;
  }

  /**
   * Get all AuditLog records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllAuditLog(): Promise<AuditLogModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new AuditLog record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertAuditLog(data: AuditLogModel[]): Promise<AuditLogModel[]> {
    const structured = data.map((item) => CreateData(AuditLogModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all AuditLog records
   */
  async purgeAllAuditLog(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List AuditLog records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listAuditLog(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[AuditLogModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get audit_log by Id index
   * This function gets data by index.
   */
  async getAuditLogById(
    id: string,
  ): Promise<AuditLogModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) audit_log by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAuditLogById(
    id: string,
    data: AuditLogModel
  ): Promise<AuditLogModel[]> {
    const index = createIndexId(
      id
    );

    const values = AuditLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete audit_log by Id index
   */
  async deleteAuditLogById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get audit_log by CreateTimeOrgId index
   * This function gets data by index.
   */
  async getAuditLogByCreateTimeOrgId(
    create_time: string,
    org_id: string,
  ): Promise<AuditLogModel[]> {
    const index = createIndexCreateTimeOrgId(
      create_time,
      org_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) audit_log by CreateTimeOrgId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAuditLogByCreateTimeOrgId(
    create_time: string,
    org_id: string,
    data: AuditLogModel
  ): Promise<AuditLogModel[]> {
    const index = createIndexCreateTimeOrgId(
      create_time,
      org_id
    );

    const values = AuditLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete audit_log by CreateTimeOrgId index
   */
  async deleteAuditLogByCreateTimeOrgId(
    create_time: string,
    org_id: string
  ): Promise<void> {
    const index = createIndexCreateTimeOrgId(
      create_time,
      org_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get audit_log by ResourceId index
   * This function gets data by index.
   */
  async getAuditLogByResourceId(
    resource_id: string,
  ): Promise<AuditLogModel[]> {
    const index = createIndexResourceId(
      resource_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) audit_log by ResourceId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAuditLogByResourceId(
    resource_id: string,
    data: AuditLogModel
  ): Promise<AuditLogModel[]> {
    const index = createIndexResourceId(
      resource_id
    );

    const values = AuditLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete audit_log by ResourceId index
   */
  async deleteAuditLogByResourceId(
    resource_id: string
  ): Promise<void> {
    const index = createIndexResourceId(
      resource_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get audit_log by DataCreator index
   * This function gets data by index.
   */
  async getAuditLogByDataCreator(
    data_creator: string,
  ): Promise<AuditLogModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) audit_log by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAuditLogByDataCreator(
    data_creator: string,
    data: AuditLogModel
  ): Promise<AuditLogModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = AuditLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete audit_log by DataCreator index
   */
  async deleteAuditLogByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get audit_log by DataUpdater index
   * This function gets data by index.
   */
  async getAuditLogByDataUpdater(
    data_updater: string,
  ): Promise<AuditLogModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) audit_log by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAuditLogByDataUpdater(
    data_updater: string,
    data: AuditLogModel
  ): Promise<AuditLogModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = AuditLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete audit_log by DataUpdater index
   */
  async deleteAuditLogByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to AuditLogModel data array
   */
  private resultToData(values: Data[]): AuditLogModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return AuditLogModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as AuditLogModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized AuditLogModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is AuditLogModel => item !== null);
  }
}

/**
 * Convert AuditLogModel data to Value array
 */
function AuditLogModelToValues(data: AuditLogModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'action_type', type: DataType.string, defaultValue: '' },
    { key: 'resource_type', type: DataType.string, defaultValue: '' },
    { key: 'resource_id', type: DataType.string, defaultValue: '' },
    { key: 'details_json', type: DataType.string, defaultValue: null },
    { key: 'org_id', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof AuditLogModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to AuditLogModel data
 */
function AuditLogModelFromValues(values: Value[]): AuditLogModel {
  const data: Partial<AuditLogModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'action_type':
        data.action_type = ParseValue(value, DataType.string) as string;
        break;
      case 'resource_type':
        data.resource_type = ParseValue(value, DataType.string) as string;
        break;
      case 'resource_id':
        data.resource_id = ParseValue(value, DataType.string) as string;
        break;
      case 'details_json':
        data.details_json = ParseValue(value, DataType.string) as string | null;
        break;
      case 'org_id':
        data.org_id = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as AuditLogModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for CreateTimeOrgId fields
 */
function createIndexCreateTimeOrgId(
  create_time: string,
  org_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, create_time, 'create_time'),
    CreateValue(DataType.string, org_id, 'org_id'),
  ];

  return {
    fields: ['create_time', 'org_id'],
    values
  };
}
/**
 * Create index for ResourceId fields
 */
function createIndexResourceId(
  resource_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, resource_id, 'resource_id'),
  ];

  return {
    fields: ['resource_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default AuditLogORM;